version: '3.9'

services:
  sing-box:
    image: xiongli870110/singbox:1.0.2
    container_name: singbox
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      #- UUID=688db1b3-0b3f-48d9-98a2-c5574415a400     #不设置时会自动生成
      - PORT=8080
      - WS_PATH=/chat
      - LISTEN_ADDR=0.0.0.0
      - SNIFF=true
      - SNIFF_OVERRIDE=true
      - LOG_LEVEL=info
